defaults:
  - ${model}/config

model: adda

dataset:
  src: mnist
  tgt: mnist_m
  img_size: 28
  root: "/root/domain-adaptation-pytorch-lightning/data"

epoch: 20
logger: true
load: true
save: false
save_path: "/root/domain-adaptation-pytorch-lightning/pretrained"
seed: 8888
gpus: 1
